### PR TITLE
added mini study if configure flags influence runtime, and yes they do

### PR DESCRIPTION
**Pull request by psteinb**

### CODE REVIEW

**Comment by tdd11235813** [comment]
thanks for the nice tests showing influence of certain fftw compile flags.

- what does ./bench use, fftw3_threads or fftw3_omp?
  - it is possible that bench is using threads instead of OpenMP (might give that performance difference), since ./bench is compiled twice; first time it is linked against fftw3_omp and second time it is linked against fftw3_threads (just guessing) - what is your experience, can we omit enable-threads?
- what does the `$i` in `--enable-threads $i` in line [49 of your PR](https://github.com/mpicbg-scicomp/gearshifft_publication/pull/19/files#diff-4cc5fcc8b8d5e46e8a746c58ecedab05R49)
- regarding the high planning time of the second part, I found following explanation in the fftw3 [release notes](http://www.fftw.org/release-notes.html):
_Special note for distribution maintainers: Although FFTW supports a zillion SIMD instruction sets, enabling them all at the same time is a bad idea, because it increases the planning time for minimal gain. We recommend that general-purpose x86 distributions only enable SSE2 and perhaps AVX. Users who care about the last ounce of performance should recompile FFTW themselves._ 
- you do not need to provide enable-sse separately, enable-sse2 is sufficient ([see here](https://github.com/FFTW/fftw3/blob/master/configure.ac#L115))
  - subsequently, 128bit AVX is useless on Intel (but might help on AMD)
- so as general recommendation for "modern" systems and for an isolated setup with just a single SIMD flag `--enable-sse2` is the way to go?
  - it is interesting, that all the SIMD flags does not yield the same runtime as the single sse2 flag ... either it overwrites a SIMD flag (but configure looks good so far) or the runtime detection is not exact or the compilation of bench is wrong (see above)

**Comment by psteinb** [comment]
I moved the markdown into it's own subdirectory, the summary.md will yield the answers you seek (once I put them in)

**Comment by psteinb** [comment]
> - what does ./bench use, fftw3_threads or fftw3_omp?
>   - it is possible that bench is using threads instead of OpenMP (might give that performance difference), since ./bench is compiled twice; first time it is linked against fftw3_omp and second time it is linked against fftw3_threads (just guessing) - what is your experience, can we omit enable-threads?

It's possible, AFAIK if both enable-openmp and enable-threads is set, 
`bench` links against the libpthreads variant of libfftw.

> - what does the `$i` in `--enable-threads $i` in line [49 of your PR](https://github.com/mpicbg-scicomp/gearshifft_publication/pull/19/files#diff-4cc5fcc8b8d5e46e8a746c58ecedab05R49)

Just a remnant of my copy-and-paste madness. thanks for clapping my fingers.

> - regarding the high planning time of the second part, I found following explanation in the fftw3 [release notes](http://www.fftw.org/release-notes.html):
>   _Special note for distribution maintainers: Although FFTW supports a zillion SIMD instruction sets, enabling them all at the same time is a bad idea, because it increases the planning time for minimal gain. We recommend that general-purpose x86 distributions only enable SSE2 and perhaps AVX. Users who care about the last ounce of performance should recompile FFTW themselves._

I saw that too a long time ago and forgot about it. This small study 
proves it again.

> - you do not need to provide enable-sse separately, enable-sse2 is sufficient ([see here](https://github.com/FFTW/fftw3/blob/master/configure.ac#L115))
>   - subsequently, 128bit AVX is useless on Intel (but might help on AMD)

Good catch, thank you!

> - so as general recommendation for "modern" systems and for an isolated setup with just a single SIMD flag `--enable-sse2` is the way to go?
>   - it is interesting, that all the SIMD flags does not yield the same runtime as the single sse2 flag ... either it overwrites a SIMD flag (but configure looks good so far) or the runtime detection is not exact or the compilation of bench is wrong (see above)

Indeed this is the knowledge gain that I'd be after as well. I think it 
all depends on how the fftw compiler is called. it looks to me like the 
configure step tries to autodetect the hardware and generates 
close-to-asm code that will be put in the library or at least in the 
genfft replica that lands in libfftw.so. Most of this stuff you can only 
see after the `configure` step or the `make` step.

I personally think, this mini-study should end here. We showed that 
different fftw flags yield different runtimes, but the configure flags 
we chose give very good (if not the best) performance.

**Comment by tdd11235813** [comment]
> [..] it looks to me like the configure step tries to autodetect the hardware and generates close-to-asm code that will be put in the library or at least in the genfft replica that lands in libfftw.so [..]

.. and fftw looks for the fastest SIMD code at runtime, that's why planning is taking so long - but as we see it did not find the fastest one. 
Ok, I am going to merge this, thanks a bunch again.

**Pull request merged**
