### PR TITLE
Reduced references, smaller images, removed project structure figure.

### PR DESCRIPTION
**Pull request by tdd11235813**

### CODE REVIEW

**Comment by psteinb** [comment]
why did you remove the figure?

**Comment by tdd11235813** [comment]
too much space for too irrelevant information. A project structure is not relevant for the benchmark and belongs only to documentation, in other words, I could live without it. Did you like it? ;)

**Comment by psteinb** [comment]
I did like it yes, I looked very polished. However, I see your point. Ready for merge?

**Comment by tdd11235813** [comment]
due to possible conflicts, I would first merge your PR, if it is ready for merge, and then update/merge my branch locally to avoid loss of text ;)

**Comment by psteinb** [comment]
feel free to do that!

**Pull request merged**
