### PR TITLE
R2c versus c2c and fp32 versus fp64

### PR DESCRIPTION
**Pull request by psteinb**

### CODE REVIEW

**Comment by tdd11235813** [comment]
cool, just a little question: did you add svg on purpose to the repo? just asking because previously you removed the svgs (which helped to get more clean diffs and git workflow).

**Comment by psteinb** [comment]
errrgh, I guess that was my mistake, I'll remove the svgs again.

**Comment by tdd11235813** [comment]
ok you can merge, if you want .. I follow with update and merge on my PR then.

**Comment by psteinb** [comment]
done

**Pull request merged**
