### PR TITLE
makefile + script for gnuplot

### PR DESCRIPTION
**Pull request by tdd11235813**
Probably you will not like that, but I was curious about dynamic gnuplot diagrams.
The idea came from the latex output issues in R (tex and tikzDevice were not really usable, but I have not tried too much to circumvent this).

The static layout part contains 1d, 2d and 3d (1st diagram column) and powerof2, radix357 and oddshape (2nd column) and inplace vs. outplace.
The dynamic layout part involves real vs. complex or precisions (float, double, ..) or libraries or devices. It can be selected by command-line arguments as demonstrated in the makefile.
I have not touched your version, but created a new folder figures/gnuplot instead.
I'll send you an email with an PDF, since upload does not seem to work here.

Edit: many diagrams of that size (3x2) will be too big for the paper. maybe it is better to pick specific diagrams. An overall comparison pdf file or set of png files must be available, but this could happen online in gearshifft repository, for example.

### CODE REVIEW

**Comment by psteinb** [comment]
As discussed offline, I am wondering if this could/should go into gearshifft directly. This way, we have a quick way of plotting the results in gearshifft with just the dependency on gnuplot, which I consider very lightweight...how do you feel?

**Comment by tdd11235813** [comment]
> Automatic comparison plots of Time_{Total, FFT, Upload, PlanInitFwd} between {device,library,precision} types and files. Error bars when error>1%

[pdf file](https://cloudstore.zih.tu-dresden.de/public.php?service=files&t=38d54eda0b8e2d0de7256c4f5e69ab24) (~45MiB)
...

**Comment by tdd11235813** [comment]
In figures/gnuplot you run either make or
```bash
make compare # create statistics by compare.r script (simplified version of original compare script)
make plot # runs gnuplot to generate tex/pdf diagrams
make pdf # compiles the tex files to the figures_master.pdf
```
Do not use parallel make (-j ..), since parallel processes are started on its own, and I have not integrated interdependency checks in that Makefile.
Now you can merge if you want ;)

edit: later we could move this auto-plot stuff to gearshifft, but the bash script is not that portable. cmake could help with the results generation, the R script could be more lightweight (remove libraries ggplot ..) .. maybe the gnuplot invocation loops can be done with R as well (with multi-thread support?)

**Comment by psteinb** [comment]
I'll merge this here as I think it's great addition. I strongly agree that this should go into gearshifft directly

**Pull request merged**
