### PR TITLE
Updated formatting

### PR DESCRIPTION
**Pull request by psteinb**
please have a look at the mindmap included in this PR

### CODE REVIEW

**Comment by tdd11235813** [comment]
yeah, much better now :) btw, is `tikzfigures.aux` required ?
edit: after this PR I am going to merge some fixes due to the increased font size, and include a slide for a gearshifft overview.

**Comment by psteinb** [comment]
Not at all, I'll remove it.

**Comment by psteinb** [comment]
done, ready for merge!

**Comment by tdd11235813** [comment]
maybe the font size does not need to be reset to 10pt and I already fixed the parts. I gonna merge this now to have a base and we can discuss this in the upcoming PR.

**Comment by psteinb** [comment]
ok, great. I didn't see that fix. But some of slides looked a bit weird 
on my machine when leaving `11pt` as the default font size. Looking 
forward to your PR. I'll continue on my side as well by adding some more 
content.

**Pull request merged**
