### PR TITLE
Extents

### PR DESCRIPTION
**Pull request by psteinb**
ready for review:
- 4 extent files meant as configs to gearshifft
- python script to generate them
- do we need a script/Makefile to automate generation?

### CODE REVIEW

**Comment by tdd11235813** [comment]
cool, nice script. makefile is nice to have. 
according to the python script: probably radix-19 generates cumbersome extents like 361,361,6859. cufft would require 30 GB GPU RAM for solving this. Since, only one prime of the factorials needs to be an unsupported one, 2^k \* 19 would be sufficient for an arbitrary-like extent. clfft is not able to solve these kinds of extents anyway. fftw can handle these arbitrary extents, and there even is a way to generate fftw codelets to even solve such primes efficiently (this will not be part of this publication due 
to our time restrictions, but just as information):

If you need efficient transforms of other sizes, you can use FFTW’s code generator, [...]
http://www.fftw.org/doc/Introduction.html

**Comment by psteinb** [comment]
so for the radix-19 stuff in 2D, you suggest to do `(2^n)*19` and for 3D `(2^k)*(2^n)*19` or something along those lines?

**Comment by tdd11235813** [comment]
ok, it seems that #1 already is included in this PR #2. If so, I would merge this and close #1. 
Btw, I like the abstract for now :) 

According to your last question: A single extent, supported by the libraries, can be a number which is factorized into power of primes of 2, 3, 5, 7, (11, 13). So 7 \* 5 is supported. 
If you add a prime like 19, you get an "unsupported" size.
So to generate such an unsupported combination of powers, 2^k \* 19 is sufficient, we also could take 17 of course.
If you now have 2D or 3D, then (17 \* 2^r) x (17 \* 2^s) x (17 \* 2^t) is "maximal unsupported" :D 
clfft would require all sizes to be a supported one, otherwise it fails with "CLFFT_NOTIMPLEMENTED".

**Comment by psteinb** [comment]
got it, I'll update this PR and yes it contains #1 ... I wanted to get going and didn't pay attention

**Comment by tdd11235813** [comment]
ok. I plan to run the benchmarks over weekend. At the moment our GPUs are 100% busy anyway ;)

**Comment by psteinb** [comment]
would that be ok?

```
==> extents_2D.conf <==
#radix-19
19,1024,1024
361,512,512
6859,128,128
19,243,243
361,81,81
6859,27,27
19,25,25
361,25,25
6859,25,25

==> extents_3D.conf <==
#radix-19
19,1024,1024
361,512,512
6859,128,128
19,243,243
361,81,81
6859,27,27
19,25,25
361,25,25
6859,25,25
```

**Comment by tdd11235813** [comment]
It turned out, that by far the best data set for a worst-case benchmarking of inefficient extents is using powers of a single prime numbers like 19, since a mixed-radix implementation of FFT/Cooley-Tukey still benefits from power of 2s in the factorization of an extent accordingly. So I reverted the code changes to pure radix19 generation as well as applied some fixes to the generated ranges and conf files, see [this commit](https://github.com/mpicbg-scicomp/gearshifft_publication/commit/25399e4fe2c0748ce089637967fd2ad49ef99c0a). Sorry so much for misleading.

Just for the records, benchmarking two extents with similar size, but different primes, yields:

```
19^5 = 2476099 took  422 ms 
19*2^17 = 2490368 took 7 ms
```

Inplace Real, float, cufft were used.

**Comment by psteinb** [comment]
great thanks, then I'll run the extents on my Pascal over the week-end as well, feel free to send PRs for the output data

**Pull request merged**
