### PR TITLE
started to write up introduction

### PR DESCRIPTION
**Pull request by psteinb**
please leave this PR open until I give green-light for cross reading

### CODE REVIEW

**Comment by psteinb** [comment]
@tdd11235813 can you please try to build this? biber 2.5 exists on me with code 1 with no clear error message besides a warning that appears to be a known issue with perl

**Comment by psteinb** [comment]
done, the article builds now, I'll continue on with the benchmark design based on the plan-create-and-execute idiom

**Comment by psteinb** [comment]
as the bibliography will be needed by the main tex file to build, feel free to merge this and postpone your feedback ... although providing feedback now would be ideal

**Comment by tdd11235813** [comment]
cool, thanks for the great update and sorry for my delayed answer.
The files are working here, pdf is created without problems.
There are some small things, but not content related, so I want to make a separate PR right now after merging this, so it is easier to see my change requests :)

**Pull request merged**
