### PR TITLE
update to motivation section

### PR DESCRIPTION
**Pull request by tdd11235813**
- fourier -> Fourier
- ~~complex -> real~~ (edit: this was a mistake by my own, sorry)
- \mathcal{o} -> \mathcal{O}
...

### CODE REVIEW

**Comment by tdd11235813** [comment]
- fixed index of X[k1+k2n2] to X[k1+k2n1]
- tried to explain radix and butterfly a little bit more in detail

**Comment by psteinb** [comment]
please let me know when this is ready for merge, thanks

**Comment by tdd11235813** [comment]
I am about to add a paragraph on shapeness of transforms (to define powerof2, radix357, oddshape) ...

**Comment by tdd11235813** [comment]
you can merge this, tomorrow I would start with the latex layout of the diagrams.

**Pull request merged**
