### PR TITLE
added review comments by cbg member

### PR DESCRIPTION
**Pull request by psteinb**

### CODE REVIEW

**Comment by tdd11235813** [comment]
thanks for the fixes. Just a minor thing: "an FFT" sounds better than "a FFT" to me, so I would use first one (see line 82 implementation.tex).
Btw, do you want to integrate further reviews in here?

**Comment by psteinb** [comment]
fixed. I'd prefer one PR per proofreading if possible.

**Comment by tdd11235813** [comment]
k, good to know, so I merge this now. Thanks again for the improvements! :)

**Comment by tdd11235813** [comment]
ah something went wrong with merging. And I realized that there is a commit missing?

**Comment by tdd11235813** [comment]
seems merge has been done, but this PR has not been updated. While merging I got an internal server error...

**Comment by psteinb** [comment]
let me see if I can fix the merge conflicts and push

**Comment by psteinb** [comment]
weird, I also see this:

```
$ git push origin master
Total 0 (delta 0), reused 0 (delta 0)
remote: Unexpected system error after push was received.
remote: These changes may not be reflected on github.com!
remote: Your unique error code: e6679ec9efabe4d67413c417f92a900f
To git@github.com:psteinb/gearshifft_publication.git
    4d6e056..bde4c41  master -> master
```

**Comment by tdd11235813** [comment]
pull, fetch upstream and the like work. So the changes are in the history as expected. So we need to delete this PR, since it has not been updated after merge.

**Comment by psteinb** [comment]
I pushed an update to my fork that should land in this PR ... strange that it doesn't. any idea on how to proceed?

**Comment by psteinb** [comment]
according to this [status page](https://status.github.com/) there is a 
service outage of github since around 9pm

**Comment by tdd11235813** [comment]
this PR turned into a ghost. The change you locally added needs to be repushed on another branch or at least create a new pull request based on your current branch.
ok, service outage seems to be the explanation, so I close this PR now.

**Pull request closed without merging**
