### PR TITLE
Plot style

### PR DESCRIPTION
**Pull request by psteinb**
in case we are force to produce b&w plots, this still layout is still hard to transform, but for now, I feel that the plots are more clear and more easy to digest

### CODE REVIEW

**Comment by tdd11235813** [comment]
yes it definitely looks better. 
only one thing, probably the lib is missing in the legend, see here:
fig6_legend_missing

**Comment by psteinb** [comment]
I'll look into that

**Comment by psteinb** [comment]
fixed

**Comment by tdd11235813** [comment]
thanks a bunch for these fancy improvements :)

**Pull request merged**
