### PR TITLE
removed CLI table. Added first results of runtime verification.

### PR DESCRIPTION
**Pull request by tdd11235813**
~ WIP ~

This PR relates to #46

### CODE REVIEW

**Comment by tdd11235813** [comment]
added some plots to illustrate gearshifft's almost zero overhead (for K80, cufft, inplace r2c, float).
text is not finished yet, so wait with merging.

**Comment by psteinb** [comment]
great to see that everything is coming together. I am looking forward to 
the description. Please document the steps taken to produce the data. 
maybe in a new directory `scripts/validation`. we also need to document 
in the publication repo how we obtained the gearshifft csv files. feel 
free to put slurm scripts into the respective results directory. I;d 
like to try to make this publication as reproducible as possible.

**Comment by tdd11235813** [comment]
merged your PR #48 #49 #50 #52 #53.
That was fun, `git diff --word-diff` did a good job to guide me through this battlefield, at least I hope to get all changes right. I now would proceed with this PR and your recommendations.

**Comment by psteinb** [comment]
sounds good to me. good luck!

**Comment by tdd11235813** [comment]
I suggest to put the cufft standalone code and the validation + run scripts into gearshifft repo, since it is relevant there, too. And it would be more convenient to refer to it in the paper, what do you think?

**Comment by tdd11235813** [comment]
... hmm a big disadvantage is, that each user of this repository will download these files as well, which I would dislike.
well, I gonna put these files into publication repo as you suggested; we should refer to it in the gearshifft repo, so we can keep the reference to gearshifft github url in the paper.

**Comment by tdd11235813** [comment]
- improved text on gearshifft validation
- code for validation and job scripts added
  - for the sake of correctness I rerun the validation and I am waiting for the job scheduler again (Taurus is busy)
  - (csv also mistakenly contained Inplace Complex instead of Inplace Real, which however did not affect the diagrams)
- fftw wisdom explained more in detail (wisdom -> FFTW_PATIENT)
  - in the results section I removed the warning which discourages consequently using wisdom
  - ... I mentioned the phenomenon that PATIENT mode should provide faster transforms than MEASURE and although I used the same flags, we have to find out, if plan-search is deterministic -- even in a multi-thread environment (read doc or ask fftw devs)
- reduced words in abstract to fit 150 words limit

**Comment by psteinb** [comment]
Fine with me.

**Comment by psteinb** [comment]
Ok, that's a lot of work you put into this PR. Thanks. I highly appreciate that. Feel free to merge at will.

**Comment by psteinb** [comment]
btw, you could think about moving the overhead/validation analysis into the implementation section. I think the context there would be more appropriate

**Comment by tdd11235813** [comment]
this merge happens more due to its growing size. Still had no time to proofread all my text, I hope to finish it this afternoon ..

I also think about your suggestion to move the validation part to the implementation section (atm I would tend to leave it in the results section as it is more a result as a consequence of an implementation than an implementation detail).

**Comment by psteinb** [comment]
ok, that's all fine with me

**Pull request merged**
