### PR TITLE
Results

### PR DESCRIPTION
**Pull request by psteinb**
*please keep this open until further notice*, I am still unclear if one PR for this large section will work out ... we'll find out I guess

### CODE REVIEW

**Comment by psteinb** [comment]
I fixed a couple of things with ggplot, latex and more. I hence suggest to merge this in now even though the content is not finished

**Comment by tdd11235813** [comment]
ok, I am checking this out right now and merge then

**Comment by tdd11235813** [comment]
do you have an idx file for index generation? otherwise makeidx is not needed (I got error here that no idx file was found).
I would merge now anyway and would continue with the plot layout in latex.

**Comment by psteinb** [comment]
I am not sure what you mean? Which command is generating the .idx file?

**Comment by tdd11235813** [comment]
we can comment \usepackage{makeidx}, if we do not have indexed words at the moment, otherwise it might execute makeindex (Kile runs further tools if required, but this happens after pdf compilation, so no real problem here).

**Comment by psteinb** [comment]
ok, I was a bit lost here. I have no objections removing yet another dependency

**Pull request merged**
