### PR TITLE
Dual comparison

### PR DESCRIPTION
**Pull request by psteinb**
this PR contains first plots with the data currently residing inside the repo

### CODE REVIEW

**Comment by psteinb** [comment]
@tdd11235813 if our measurements are correct, these results are exciting

**Comment by tdd11235813** [comment]
yes great to see the first results, nice work. 
- can you fix the legend for float and double? I see only empty boxes here. 
- the results seem to be wrong or at least misleading, see following:

cufft

```
----------------------------------------------------------------------
Inplace, Real, float, Dim=1, Kind=powerof2 (2), Ext=16777216
----------------------------------------------------------------------
            Time_Device [ms]:          28.9898 [avg]
        Time_Allocation [ms]:         0.377934 [avg]
          Time_PlanInit [ms]:         0.952365 [avg]
            Time_Upload [ms]:          8.93547 [avg]
               Time_FFT [ms]:          4.85732 [avg]
              Time_iFFT [ms]:          4.82282 [avg]
          Time_Download [ms]:          8.91986 [avg]
       Time_PlanDestroy [ms]:         0.398942 [avg]
             Time_Total [ms]:          30.7199 [avg]
   Size_DeviceBuffer [bytes]:      6.71089e+07 [avg]
     Size_DevicePlan [bytes]:      6.71089e+07 [avg]
 Size_DeviceTransfer [bytes]:      6.71089e+07 [avg]
```

clfft

```
----------------------------------------------------------------------
Inplace, Real, float, Dim=1, Kind=powerof2 (2), Ext=16777216
----------------------------------------------------------------------
            Time_Device [ms]:          138.004 [avg]
        Time_Allocation [ms]:        0.0018672 [avg]
          Time_PlanInit [ms]:          15.7786 [avg]
            Time_Upload [ms]:          13.0279 [avg]
               Time_FFT [ms]:          1.41249 [avg]
              Time_iFFT [ms]:          15.4585 [avg]
          Time_Download [ms]:          10.7392 [avg]
       Time_PlanDestroy [ms]:         0.463028 [avg]
             Time_Total [ms]:          154.248 [avg]
   Size_DeviceBuffer [bytes]:      6.71089e+07 [avg]
     Size_DevicePlan [bytes]:      6.81574e+07 [avg]
 Size_DeviceTransfer [bytes]:      6.71089e+07 [avg]
```

**Comment by psteinb** [comment]
> - can you fix the legend for float and double? I see only empty boxes here.

Can you point me to the file where this happens, please? there are 
already quite many. :)

> - the results seem to be wrong or at least misleading, see following:

I admit the 1D case looks quite weird as clfft stops quite early. for 
the sake of a xcheck, could please you dump the results for 1GB powerof2 
real (I'll parse through the csv files to make sure, I didn't screw up)

**Comment by tdd11235813** [comment]
it was a problem with gwenview not showing the lines in that boxes. viewnior is fine with it.

There is quite a gap in the times (clfft):
time device covers upload + execute_forward + init_backward + execute_backward + download.
time device is measured with CPU Timer, but upload + execute_forward + execute_backward + download are measured with OpenCL Timer on device. I have tested with synchronised queues, but still the same effect, that CPU time is much higher than times on device.

**Comment by psteinb** [comment]
alright, I found why the 1D plots stop so early for clfft:

```
"ClFFT","Outplace","Real","double",1,"powerof2",8388608,0,0,0,"OpenCL error CLFFT_NOTIMPLEMENTED [4097] clfft.hpp:326 clfftBakePlan(plan_, 1, &queue_, nullptr, nullptr)",0,0,0,0,0,0,0,0,0,1.34218e+08,0,0,95
```

looks like a 32bit problem to me. ;)

**Comment by psteinb** [comment]
why don't we merge this PR and then continue discussing the plots offline as the PR contains the plotting script and the Makefile ( I guess I should have separated the code from the plots )
what do you think?

**Comment by tdd11235813** [comment]
agreed.
Just to "answer" your question: it seems, clfft cannot handle large sizes for all cases, inplace_real seems to quit early while inplace_complex is still happy for 1GB data.

cufft

```
----------------------------------------------------------------------
Inplace, Complex, float, Dim=1, Kind=powerof2 (2), Ext=134217728
----------------------------------------------------------------------
            Time_Device [ms]:          318.699 [avg]
        Time_Allocation [ms]:          1.39118 [avg]
          Time_PlanInit [ms]:          1.65978 [avg]
            Time_Upload [ms]:          114.841 [avg]
               Time_FFT [ms]:           54.309 [avg]
              Time_iFFT [ms]:          54.2098 [avg]
          Time_Download [ms]:          95.2443 [avg]
       Time_PlanDestroy [ms]:          0.85281 [avg]
             Time_Total [ms]:          322.603 [avg]
   Size_DeviceBuffer [bytes]:      1.07374e+09 [avg]
     Size_DevicePlan [bytes]:      1.07374e+09 [avg]
 Size_DeviceTransfer [bytes]:      1.07374e+09 [avg]
```

clfft

```
----------------------------------------------------------------------
Inplace, Complex, float, Dim=1, Kind=powerof2 (2), Ext=134217728
----------------------------------------------------------------------
            Time_Device [ms]:          923.269 [avg]
        Time_Allocation [ms]:         0.001941 [avg]
          Time_PlanInit [ms]:          12.2774 [avg]
            Time_Upload [ms]:          150.773 [avg]
               Time_FFT [ms]:          15.1687 [avg]
              Time_iFFT [ms]:          15.1716 [avg]
          Time_Download [ms]:          116.657 [avg]
       Time_PlanDestroy [ms]:           1.5514 [avg]
             Time_Total [ms]:            937.1 [avg]
   Size_DeviceBuffer [bytes]:      1.07374e+09 [avg]
     Size_DevicePlan [bytes]:      1.09052e+09 [avg]
 Size_DeviceTransfer [bytes]:      1.07374e+09 [avg]
```

**Comment by psteinb** [comment]
interesting. Is that something the authors are aware of? 
In any case, I'll merge now after these last 2 commits (changing from Time_FFT to Time_Total). the interesting thing is that the Total Time is apparently smaller for cufft across the board than for clfft. that is something to look out for in terms of time measurements. We might wanna try Time_Total-(Time_Upload+Time_Download) or something along those lines as a cross check.

**Comment by tdd11235813** [comment]
yeah I definitely have to take a look on the measurements again.
When I use CPU Timer only, following results are obtained:

```
----------------------------------------------------------------------
Inplace, Complex, float, Dim=1, Kind=powerof2 (2), Ext=134217728
----------------------------------------------------------------------
            Time_Device [ms]:          926.652 [avg]
        Time_Allocation [ms]:        0.0018082 [avg]
          Time_PlanInit [ms]:          12.3249 [avg]
            Time_Upload [ms]:          155.109 [avg]
               Time_FFT [ms]:          328.303 [avg]
              Time_iFFT [ms]:          324.584 [avg]
          Time_Download [ms]:           118.65 [avg]
       Time_PlanDestroy [ms]:          1.55253 [avg]
             Time_Total [ms]:          940.532 [avg]
   Size_DeviceBuffer [bytes]:      1.07374e+09 [avg]
     Size_DevicePlan [bytes]:      1.09052e+09 [avg]
 Size_DeviceTransfer [bytes]:      1.07374e+09 [avg]
```

**Comment by psteinb** [comment]
but the Time_Total appears not to be affected for clfft! that is good 
news though.

**Comment by psteinb** [comment]
Let me correct myself, from your timing results, only Time_FFT and 
Time_iFFT is affected by the timers. that is even more good news than 
stated before.

**Pull request merged**
