### PR TITLE
Placiness

### PR DESCRIPTION
**Pull request by psteinb**

### CODE REVIEW

**Comment by psteinb** [comment]
shoot, I clicked too fast. Let me fix the conflicts first

**Comment by psteinb** [comment]
you know what never mind, feel free to merge, I'll resubmit this PR then

**Comment by tdd11235813** [comment]
oh now you got me, lol - I thought this was the other PR. Let's check the differences, you can prepare this PR meanwhile.

**Comment by psteinb** [comment]
updated the PR

**Comment by psteinb** [comment]
reopened this PR

**Pull request merged**
