### PR TITLE
Adding hierarchical structure

### PR DESCRIPTION
**Pull request by psteinb**
one problem I observed was that the page numbers don't appear, but maybe that is something for a future PR

### CODE REVIEW

**Comment by tdd11235813** [comment]
page numbers are shown as of #75 , however it was not mentioned there.
gonna merge this, thanks for the fixes.

**Comment by psteinb** [comment]
but this PR already included #75

**Comment by tdd11235813** [comment]
hmm check your local beamerthemecustom.sty and compare with [this line](https://github.com/mpicbg-scicomp/gearshifft_publication/pull/75/files#diff-6d532f67c25822da3b30124500eee898R50).

**Comment by psteinb** [comment]
saw it, they pop up now. thanks!

**Pull request merged**
