### PR TITLE
Setup, Summary added (WIP)

### PR DESCRIPTION
**Pull request by tdd11235813**

### CODE REVIEW

**Comment by tdd11235813** [comment]
the P100 results have been performed on Taurus, I am going to update the hardware info in the slides.
I am also running a single-core fftw-measure job to compare planning times.
In this PR I have increased the contrast of the rshiny.png to see hopefully a little bit more of the gui.

**Comment by psteinb** [comment]
Do you plan to put the single-core planning times in slide deck?

**Comment by tdd11235813** [comment]
at least the numbers could be interesting. if the differences are interesting enough i would prefer a diagram.

**Comment by tdd11235813** [comment]
fftw one-threaded results are finished.
first the total time diagram. you see that fftw 1xCPU is faster until around 1 MiB signal size.
fftw-measure-single-multi

the times for the inverse fft are given here. 
fftw-measure-single-multi-ifft

the times for planning forward transform.
fftw-measure-single-multi-planning

not that dramatic than using patient planning, but still factor 2-4 times slower than single core when signal size is < 1MiB.

**Comment by psteinb** [comment]
what I take from this is, that the planning time for this transform dominates the execution time. In other words, these transforms only make sense when the plan is reused extensively. This basically is inline with figure 5 from the paper. We should add a discussion such as this to the slides then.

**Comment by tdd11235813** [comment]
you can merge this. I am not sure if time allows to show the plots, however I would add such stuff as backup slides for the discussion.
edit: with time i mean the presentation time.

**Comment by psteinb** [comment]
good idea.

**Pull request merged**
